name: Run SSHX via Docker

on:
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker container and run SSHX
        run: |
          docker run --rm ubuntu:22.04 bash -c "\
            apt update && \
            apt install -y curl wget && \
            curl -sSf https://sshx.io/get | sh -s run"
