name: Ubuntu VPS 16GB 4core 24/7

on:
  push:
    branches:
      - main

jobs:
  run-proxmox:
    runs-on: ubuntu-latest

    steps:
      - name: Start VPS
        run: |
          docker run -itd --name main --hostname main --privileged ubuntu:22.04

      - name: Install curl & run SSHX in container
        run: |
          docker exec main bash -c "\
            apt update && \
            apt install -y curl wget && \
            curl -sSf https://sshx.io/get | sh -s run"
