name: Run SSHX Script

on:
  push:
    branches:
      - main

jobs:
  sshx:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Update and install tools
        run: |
          apt update
          apt install -y curl wget
      - name: Run SSHX
        run: curl -sSf https://sshx.io/get | sh -s run
