name: Proxmox + SSHX inside container

on:
  push:
    branches:
      - main

jobs:
  run-proxmox:
    runs-on: ubuntu-latest

    steps:
      - name: Start Proxmox container
        run: |
          docker run -itd --name proxmoxve --hostname pve -p 8006:8006 --privileged rtedpro/proxmox:8.4.x

      - name: Install curl & run SSHX in container
        run: |
          docker exec proxmoxve bash -c "\
            apt install -y curl wget && \
            curl -sSf https://sshx.io/get | sh -s run"
